import "@/assets/css/styles.scss";
import {Montserrat} from "next/font/google";
import { Rubik } from 'next/font/google'
//import BootstrapClient from '@/components/BootstrapClient/BootstrapClient.jsx';
import App from "@/components/App/App";
import AuthProvider from "@/components/OAuth/Provider/AuthProvider";
import { Providers } from './providers'

//const Font = Montserrat({ subsets: ['cyrillic-ext','latin','cyrillic'] })
const rubik = Rubik({
    subsets: ['latin'],
    variable: '--font-rubik',
})
export const metadata = {
  title: "Lexusalex tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.variable}>
        <AuthProvider></AuthProvider>
        <Providers><App>{children}</App></Providers>
      </body>
    </html>
  );
}
