version: "3.8"
services:
    backend-php-cli:
        build:
          context: backend/docker
          dockerfile: backend-php-cli/Dockerfile
        environment:
         POSTGRES_HOST: backend-postgres
         POSTGRES_USER: lexusalex-tech
         POSTGRES_PASSWORD: lexusalex-tech
         POSTGRES_DB: lexusalex-tech
         POSTGRES_CHARSET: utf-8
         POSTGRES_PORT: 5432
         APPLICATION_ENVIRONMENT: development
         APPLICATION_DEBUG: 1
         JWT_ENCRYPTION_KEY: secret
         JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.key
         JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.key
        volumes:
          - ./:/lexusalex-tech
        secrets:
          - jwt_public.key
          - jwt_private.key
    backend-nginx:
        build:
          context: backend/docker
          dockerfile: backend-nginx/Dockerfile
        ports:
          - "8080:8080"
        volumes:
          - ./:/lexusalex-tech
        depends_on:
          - backend-php-fpm
    backend-php-fpm:
        build:
          context: backend/docker
          dockerfile: backend-php-fpm/Dockerfile
        environment:
          POSTGRES_HOST: backend-postgres
          POSTGRES_USER: lexusalex-tech
          POSTGRES_PASSWORD: lexusalex-tech
          POSTGRES_DB: lexusalex-tech
          POSTGRES_CHARSET: utf-8
          POSTGRES_PORT: 5432
          APPLICATION_ENVIRONMENT: development
          APPLICATION_DEBUG: 1
          JWT_ENCRYPTION_KEY: secret
          JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.key
          JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.key
        volumes:
          - ./:/lexusalex-tech
        secrets:
          - jwt_public.key
          - jwt_private.key
    backend-postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: lexusalex-tech
            POSTGRES_PASSWORD: lexusalex-tech
            POSTGRES_DB: lexusalex-tech
        volumes:
            - backend-postgres:/var/lib/postgresql/data
            - ./:/lexusalex-tech
        ports:
            - "5432:5432"
secrets:
    jwt_public.key:
        file: ./backend/docker/secrets/jwt_public.key
    jwt_private.key:
        file: ./backend/docker/secrets/jwt_private.key
volumes:
    backend-postgres: