version: "3.8"
services:
    backend-php-cli:
        build:
          context: backend/docker
          dockerfile: backend-php-cli/Dockerfile
        environment:
         POSTGRES_HOST: backend-postgres
         POSTGRES_USER: lexusalex-tech
         POSTGRES_PASSWORD: lexusalex-tech
         POSTGRES_DB: lexusalex-tech
         POSTGRES_CHARSET: utf-8
         POSTGRES_PORT: 5432
         APPLICATION_ENVIRONMENT: development
         APPLICATION_DEBUG: 1
        volumes:
          - ./:/lexusalex-tech