services:
    backend-php-cli:
        build:
          context: backend/docker
          dockerfile: backend-php-cli/Dockerfile
        environment:
         POSTGRES_HOST: backend-postgres
         POSTGRES_USER: lexusalex-tech
         POSTGRES_PASSWORD: lexusalex-tech
         POSTGRES_DB: lexusalex-tech
         POSTGRES_CHARSET: utf-8
         POSTGRES_PORT: 5432
         APPLICATION_ENVIRONMENT: development
         APPLICATION_DEBUG: 1
         MAILER_HOST: backend-mailer
         MAILER_PORT: 1025
         MAILER_USER: test
         MAILER_PASSWORD: test
         MAILER_ENCRYPTION: tcp
         MAILER_FROM_EMAIL: test@test.test
         MAILER_FROM_EMAIL_NAME: lexusalex-tech system
         FRONTEND_URL: http://127.0.0.1
         JWT_ENCRYPTION_KEY: secret
         JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.key
         JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.key
        volumes:
          - ./:/lexusalex-tech
        secrets:
          - jwt_public.key
          - jwt_private.key
    backend-nginx:
        build:
          context: backend/docker
          dockerfile: backend-nginx/Dockerfile
        ports:
          - "8080:8080"
        volumes:
          - ./:/lexusalex-tech
        depends_on:
          - backend-php-fpm
    backend-php-fpm:
        build:
          context: backend/docker
          dockerfile: backend-php-fpm/Dockerfile
        environment:
          POSTGRES_HOST: backend-postgres
          POSTGRES_USER: lexusalex-tech
          POSTGRES_PASSWORD: lexusalex-tech
          POSTGRES_DB: lexusalex-tech
          POSTGRES_CHARSET: utf-8
          POSTGRES_PORT: 5432
          APPLICATION_ENVIRONMENT: development
          APPLICATION_DEBUG: 1
          MAILER_HOST: backend-mailer
          MAILER_PORT: 1025
          MAILER_USER: test
          MAILER_PASSWORD: test
          MAILER_ENCRYPTION: tcp
          MAILER_FROM_EMAIL: test@test.test
          MAILER_FROM_EMAIL_NAME: lexusalex-tech system
          FRONTEND_URL: http://127.0.0.1
          JWT_ENCRYPTION_KEY: secret
          JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.key
          JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.key
        volumes:
          - ./:/lexusalex-tech
        secrets:
          - jwt_public.key
          - jwt_private.key
    backend-postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: lexusalex-tech
            POSTGRES_PASSWORD: lexusalex-tech
            POSTGRES_DB: lexusalex-tech
        volumes:
            - backend-postgres:/var/lib/postgresql/data
            - ./:/lexusalex-tech
        ports:
            - "5432:5432"
    backend-mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"
    frontend-node-cli:
        build:
          context: frontend/docker
          dockerfile: frontend-node/Dockerfile
        volumes:
          - ./:/lexusalex-tech
    frontend-nginx:
        build:
          context: frontend/docker
          dockerfile: frontend-nginx/Dockerfile
        ports:
           - "80:80"
        depends_on:
           - frontend-node
    frontend-node:
        build:
          context: frontend/docker
          dockerfile: frontend-node/Dockerfile
        environment:
          NODE_ENV: development
          AUTHORIZE_PATH: http:/127.0.0.1/api/authorize
          TOKEN_PATH: http:/127.0.0.1/api/token
          CLIENT_ID: frontend
          REDIRECT_URL: http://127.0.0.1/oauth
          NAME: "Lexusalex Tech"
        volumes:
          - ./:/lexusalex-tech
        command: npm run dev
        tty: true
secrets:
    jwt_public.key:
        file: ./backend/docker/secrets/jwt_public.key
    jwt_private.key:
        file: ./backend/docker/secrets/jwt_private.key
volumes:
    backend-postgres: